### ISSUE TITLE
Не запускаются примеры

### ISSUE THREAD

**Issue by Melmarn** [natasha/ipymarkup#1]
Приветствую! После установки ipymarkup пробую запустить примеры [https://nbviewer.jupyter.org/github/natasha/ipymarkup/blob/master/docs.ipynb](https://nbviewer.jupyter.org/github/natasha/ipymarkup/blob/master/docs.ipynb). В результате  - ошибка 

> cannot import name 'HtmlMarkup' from 'ipymarkup.markup'
и далее с другим примером

> cannot import name 'show_ascii_markup' from 'ipymarkup'

**Comment by kuk** [comment]
Может быть версия не та установлена , попробуйте `pip install -U ipymarkup==0.5.0`

**Comment by Melmarn** [comment]
Пробовала, не помогло. Проверила requirements.txt - всё нормально.

**Comment by Melmarn** [comment]
Разобрались. Пакет установился не в то окружение...
