### ISSUE TITLE
Source distribution for PyPI

### ISSUE THREAD

**Issue by cbrew** [natasha/ipymarkup#4]
Could you make a source distribution on PyPI?  That would make it easier for my colleagues within Facebook to use and perhaps contribute improvements to your code. We have import tools that make this go smoothly for us, but we need a source distribution if possible, so that we can have a lot of clarity on exactly what we are using, and can be sure to be maximally helpful to the open source community.

I think [this gist ](https://gist.github.com/gboeing/dcfaf5e13fad16fc500717a3a324ec17 ) says how to make a source distribution for PyPI.

**Comment by kuk** [comment]
There is a source distribution, see https://pypi.org/project/ipymarkup/0.7.0/#files (ipymarkup-0.7.0.tar.gz (12.1 kB))

**Comment by cbrew** [comment]
Great. Don't know how I missed it.

Chris

**Comment by cbrew** [comment]
I've worked out why I am having trouble. The issue is that setup.py refers
to the requirements folder, which is present in the github repository but
absent from the source distribution.
The facebook internal tool looks at setup.py, and fails to find
requirements/main.txt, which it is expecting. So it would be super-helpful
if you adjusted the source distribution to include
the requirements subfolder.

Chris

**Comment by kuk** [comment]
Please try using https://pypi.org/project/ipymarkup/0.8.0/#files . Fixed the issue with requirements, do not use source dist myself, so report in case of any problems

**Comment by cbrew** [comment]
I think 0.8.0 worked. I still have some boxes to check, but our automated
process is delivering green success markers rather than errors now.

**Comment by cbrew** [comment]
Yes, all good. I can do everything I need to. 0.8.0 solves my internal install issue.
